/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: debian-s390x"
#define DATE "built on: Thu Oct 27 17:06:56 2022 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','f',
    'P','I','C',' ','-','p','t','h','r','e','a','d',' ','-','m','6',
    '4',' ','-','W','a',',','-','-','n','o','e','x','e','c','s','t',
    'a','c','k',' ','-','W','a','l','l',' ','-','W','a',',','-','-',
    'n','o','e','x','e','c','s','t','a','c','k',' ','-','g',' ','-',
    'O','2',' ','-','f','f','i','l','e','-','p','r','e','f','i','x',
    '-','m','a','p','=','/','o','p','t','/','o','p','e','n','s','s',
    'l','-','b','u','i','l','d','/','o','p','e','n','s','s','l','-',
    '3','.','0','.','2','=','.',' ','-','f','l','t','o','=','a','u',
    't','o',' ','-','f','f','a','t','-','l','t','o','-','o','b','j',
    'e','c','t','s',' ','-','f','l','t','o','=','a','u','t','o',' ',
    '-','f','f','a','t','-','l','t','o','-','o','b','j','e','c','t',
    's',' ','-','f','s','t','a','c','k','-','p','r','o','t','e','c',
    't','o','r','-','s','t','r','o','n','g',' ','-','W','f','o','r',
    'm','a','t',' ','-','W','e','r','r','o','r','=','f','o','r','m',
    'a','t','-','s','e','c','u','r','i','t','y',' ','-','D','O','P',
    'E','N','S','S','L','_','T','L','S','_','S','E','C','U','R','I',
    'T','Y','_','L','E','V','E','L','=','2',' ','-','D','O','P','E',
    'N','S','S','L','_','U','S','E','_','N','O','D','E','L','E','T',
    'E',' ','-','D','B','_','E','N','D','I','A','N',' ','-','D','O',
    'P','E','N','S','S','L','_','P','I','C',' ','-','D','O','P','E',
    'N','S','S','L','_','B','U','I','L','D','I','N','G','_','O','P',
    'E','N','S','S','L',' ','-','D','N','D','E','B','U','G',' ','-',
    'W','d','a','t','e','-','t','i','m','e',' ','-','D','_','F','O',
    'R','T','I','F','Y','_','S','O','U','R','C','E','=','2','\0'
};
